### ISSUE TITLE
Find out how to use 2 cams and how to switch between them

### ISSUE THREAD

**Issue by FabianKowatsch** [FabianKowatsch/Fusee#18]
- [x] integrated 2nd cam
- [x] switch between cameras
- [x] Render only specific objects
- [x] Ask Sarah regarding rendering specific objects
- [x] try renderlayer on child nodes
- [x] try changing renderlayers on runtime
- [x] try renderlayers on pointcloud

**Comment by FabianKowatsch** [comment]
Ask Sarah regarding rendering specific objects

**Comment by FabianKowatsch** [comment]
To determine which objects should be rendered and which should not: [RenderLayer](http://fusee3d.org/api/Fusee.Engine.Core.Scene.RenderLayer.html) component in objects
 - About 30 different layers

The [RenderLayer property of the camera component](http://fusee3d.org/api/Fusee.Engine.Core.Scene.Camera.html#Fusee_Engine_Core_Scene_Camera_RenderLayer) can then be used to determine for each camera which of the layer(s) it should render.

**Comment by Jonnyre** [comment]
How to use RenderLayer:
Declare new RenderLayer Object and add it as **first!!** SceneComponent in SceneNode.
Add this specific Render Layer in Cam Property RenderLayer

**Comment by Jonnyre** [comment]
Applies to children and can be applied/changed on runtime.
