### ISSUE TITLE
Build larger Pointcloud out of existing smaller Pointclouds

### ISSUE THREAD

**Issue by FabianKowatsch** [FabianKowatsch/Fusee#22]
- [x] build larger pointcloud
- [x] reduce point amount
- [x] build pointcloud with 15 Million points
- [x] try larger pointcloud in Fusee
- [x]  debug conversion tool provoking the byte-7 error

**Comment by LenHu404** [comment]
With the Tool Subsample, you can select between different Ways to lower the density of the Pointcloud. The three Options are Random, Space and octree-based. Random seems to fit best for our case.

https://www.cloudcompare.org/doc/wiki/index.php?title=Density
