### ISSUE TITLE
Find out how to render semi transparent objects

### ISSUE THREAD

**Issue by FabianKowatsch** [FabianKowatsch/Fusee#25]
- [x] ask Sarah regarding switching between textures( 2 spheres or 2 textures)

**Comment by LksWllmnn** [comment]
so far nothing found about transparency in fusee. completely transparent .png's are output as texture only black. 
Maybe the branch shaderEffect_alpha has something about it. Last commit by Sarah Busert July 2020.

**Comment by LksWllmnn** [comment]
Unity displays semi-transparent objects with a specific Rendering-Mode: https://docs.unity3d.com/Manual/StandardShaderMaterialParameterRenderingMode.html

Maybe Fusee can do the same with the Enum: RenderState: https://fusee3d.org/api/Fusee.Engine.Common.RenderState.html
