### ISSUE TITLE
Application Concept

### ISSUE THREAD

**Issue by FabianKowatsch** [FabianKowatsch/Fusee#5]

**Comment by LksWllmnn** [comment]
Transition from one Panoramaimage to another. 

Research simple implementation

build two panoramas and chage position in them.

Search for two images with distance of ca 10m between them.

**Comment by LksWllmnn** [comment]
Map for overview

- how to integrate
- mini map without position reference
- matterport (inspire from)

**Comment by FabianKowatsch** [comment]
look up existing technologies:

- lrpano: https://krpano.com/home/
-

**Comment by LksWllmnn** [comment]
some umls about our Porject in bwSyncAndShare under Folder: BWSyncAndShare\MuVista\Skizzen

- UseCase
- Class Diagram

+ Scene and GUI Hirarchy

(link follows as soon as maintenance work on SyncAndShare is solved)
